Lesson5
Alen-Ichshanov/Kolesa-Upgrade-FE-2021 pull request #5
Opened 2021-10-10 13:53 UTC by alen-ich

2021-10-11 04:25 UTC, wizzout requested changes
Классная работа. Вроде все вопросы решены по дз. пройдись по комментам и вот этот момент надо бы поправить — карточка не должна перекрывать модалку

![Screen Shot 2021-10-11 at 09 29 37](https://user-images.githubusercontent.com/22858436/136733104-2274e64f-d604-417e-8b26-0450af34f9e6.png)

2021-10-11 04:25 UTC, wizzout commented on src/js/main.js
> +        id:       0,
id: 0 не самое лучшее значение; лучше все таки использовать от 1

2021-10-11 04:25 UTC, wizzout commented on src/js/main.js
> +        </div>`;
понятно что строка - но можно и тут сохранить выравнивание

2021-10-11 04:25 UTC, wizzout commented on src/js/main.js
> +            <div class="product-card__price">${price} баллов</div>
не думал склонение сделать? )

2021-10-11 04:25 UTC, wizzout commented on src/js/main.js
> +<div class="modal main-container__modal" style="display: none;" id="${id}">
а нужно ли тебе переписывать модалку полностью? Ведь достаточно было обновлять контентную часть

2021-10-11 04:25 UTC, wizzout commented on src/js/main.js
> +                                    <label for="product-${id}-size1" class="modal__label-container label-container
Можно было циклом вывести. 

но не обязательно конечно

2021-10-11 04:25 UTC, wizzout commented on src/js/main.js
> +const allConcat = clothes.concat(accessories);
лишняя константа как по мне

2021-10-11 04:25 UTC, wizzout commented on src/js/main.js
> +const clothesSorted = clothes.sort(compareValues('isNew', 'desc'));
sort - мутирующая функция. после вызова сортируется и сам исходный массив. так что можно и не заводить отдельную константу - просто отсортировать и всё.

2021-10-11 04:25 UTC, wizzout commented on src/js/main.js
> +    dataArray.forEach((card) => {
можно прям несколько продуктов в одну модалку напихать? Лишний цикл

2021-10-11 04:25 UTC, wizzout commented on src/js/main.js
> +    dataArray.forEach((card) => {
А нет, оказывается ты выводишь сразу все модалки на страницу. Т

оже решение, но не думал как можно обойтись одной модалкой и заполнять ее только когда это будет нужно? 

не обязательно

2021-10-11 04:25 UTC, wizzout commented on src/js/main.js
> +generateModal(allSorted);
Два раза проходишься по одному и тому же массиву - может объеденить?

2021-10-11 04:25 UTC, wizzout commented on src/js/main.js
> +modalFunction();
из названия совсем не понятно что выполняет функция,ясно только что с модалкой связано. в принципе аналогично можно было назвать аModal (на самом деле не стоит) — лучше давать осознаные самокомментирующие названия

2021-10-11 04:25 UTC, wizzout commented on src/js/main.js
> +    buttonClose.forEach((button) => {
и снова два цикла 

попробуй сделать одну функцию которая за один проход создаст карточку модалку и слушатели для них.

2021-10-11 04:25 UTC, wizzout commented on src/js/main.js
> +            modalFunction();
напишу после всех повторений 

в програмировании есть несколько принципов опредляющих чистый код, один из них DRY  - не повторяй себя - тут у тебя вызов трех одинаковых функций с разными аргументами; 

Попробуй в условиях определить какой набор тебе нужен а в конце уже вызвать генерацию

2021-10-11 04:25 UTC, wizzout commented on src/js/main.js
> +    radio.addEventListener('click', () => {
правильнее будет слушать не click а change - все таки это input

2021-10-11 04:25 UTC, wizzout commented on src/js/main.js
> +const clothes = [
если вынести моки в отдельный файл и заимпортить тут - будет чище и понятнее; 

не обязательно

2021-10-11 04:57 UTC, wizzout commented
Кстати дедлайн на правки  12.00 12 октября

2021-10-11 10:33 UTC, alen-ich commented on src/js/main.js
> +        id:       0,
Исправил

2021-10-11 13:42 UTC, Alen-Ichshanov commented on src/js/main.js
> +            <div class="product-card__price">${price} баллов</div>
Поправил, просто рассчитывал что 1-3 баллов в цене не будет

2021-10-11 13:44 UTC, alen-ich commented on src/js/main.js
> +const allConcat = clothes.concat(accessories);
Убрал

2021-10-11 13:47 UTC, alen-ich commented on src/js/main.js
> +    radio.addEventListener('click', () => {
Исправил, у меня во время разработки не работало, я думал в change дело и на click заменил и благополучно забыл про это

2021-10-11 15:16 UTC, alen-ich commented on src/js/main.js
> +const clothesSorted = clothes.sort(compareValues('isNew', 'desc'));
Убрал лишние константы

2021-10-11 15:19 UTC, alen-ich commented on src/js/main.js
> +        </div>`;
Исправил

2021-10-11 15:53 UTC, Alen-Ichshanov commented on src/js/main.js
> +generateModal(allSorted);
Объединил

2021-10-11 15:53 UTC, alen-ich commented on src/js/main.js
> +modalFunction();
Хорошо, понял

2021-10-11 15:53 UTC, Alen-Ichshanov commented on src/js/main.js
> +    buttonClose.forEach((button) => {
Создал функция createCardModal()

2021-10-11 15:54 UTC, alen-ich commented on src/js/main.js
> +            modalFunction();
Вроде исправил, до конца не уверен что верно

2021-10-11 16:15 UTC, Alen-Ichshanov commented on src/js/main.js
> +const clothes = [
Вынес в отдельный файл mocks

2021-10-11 16:19 UTC, Alen-Ichshanov commented
test

2021-10-11 16:19 UTC, alen-ich commented
Запушил исправления в ПР

2021-10-12 04:33 UTC, wizzout approved these changes
Хорошо все сделано! Можно мержить!

2021-10-12 04:33 UTC, wizzout commented on src/js/main.js
> +        let dataValue = 0;
почему 0?

2021-10-12 04:33 UTC, wizzout commented on src/js/main.js
> +        createProductCardModal(dataValue);
и тут было бы хорошо сначала проверить что dataValue имеет значение и только тогда вызывать метод

2021-10-12 06:33 UTC, alen-ich commented on src/js/main.js
> +        let dataValue = 0;
Автоматом когда объявлял, исправил

2021-10-12 06:39 UTC, Alen-Ichshanov commented on src/js/main.js
> +        createProductCardModal(dataValue);
Такая проверка пойдет?
        if (dataValue) {
            createProductCardModal(dataValue);
        }

2021-10-12 06:40 UTC, alen-ich commented on src/js/main.js
> +        createProductCardModal(dataValue);
Добавил проверку dataValue

2021-10-12 06:43 UTC, merged